version = "1.0"

    
[main]

    [main.infos]
    name = "Garage cluster informations"

       [main.infos.node]
       type = "alert"

       [main.infos.status]
       type = "alert"

    [main.garage_conf]
    name = "Garage configuration"

        [main.garage_conf.weight]
        ask = "allocated space (Gio)"
        help = "This value is doubled by YunoHost. It sets the weight of the Garage node and, if virtualisation is enabled, creates a virtual disc of the same size."
        type = "number"
        bind = "null"

        [main.garage_conf.bootstrap_peers]
        ask = "Friend serveur adress"
        help = "Add bootstrap_peers address to connect to existing cluster"
        type = "string"
        bind = "null"
        pattern.regexp =  '[0-9a-f]{64}@((\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}|([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}):[0-9]{1,4}'
        pattern.error = "Friend server id must have id with the following form: 1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@192.168.1.1:1234 or  1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@example.tld:1234"

[danger]
services = ["__APP__"]
        
    [danger.sensible]
    name = "Danger Zone"

        [danger.sensible.rpc_secret]
        ask = "Choose/Change rpc secret"
        type = "string"
        redact = true
        bind = "rpc_secret:__INSTALL_DIR__/garage.toml"
        pattern.regexp = '^[0-9a-f]{64}$'
        pattern.error = "rpc_secret have to be a 32-byte hex-encoded random string. See https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/ for more information"
        help = "Be careful if your node is already connected to a cluster, it won't be able to connect again if you change the rpc_secret value."
