#!/bin/bash

YNH_HELPERS_VERSION="2.1" source /usr/share/yunohost/helpers

action=$1
pending_dir=$4
domain=__DOMAIN__
app=__APP__

[[ "$action" == "pre" ]] || exit 0

ynh_replace --match="server_name $domain" --replace="server_name $domain *.$domain" --file="$pending_dir/../nginx/etc/nginx/conf.d/$domain.conf"
