#!/bin/bash

source /usr/share/yunohost/helpers

garage_domains=$(yunohost app list --json | jq '.apps[] | select(.id | test("garage*")) | .domain_path')

for domain in $garage_domains;
do
    domain=${domain//\"/}
    if [[ "$domain" =~ "/" ]]
    then
        domain=${domain/\//}
        ynh_replace_special_string --match_string="server_name $domain;" --replace_string="server_name $domain *.$>
    fi
done

