#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NODE CONFIGURATION
#=================================================

$garage layout remove "$secret_node_id"

garage_layout_apply
if [ $? -ne 0 ]
then
	ynh_print_warn "Unable to remove the node. Maybe the number of node staying alive is not enough"
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd
ynh_config_remove_systemd --mount="$app""_data"
ynh_config_remove_systemd --mount="$app""_metadata"

ynh_config_remove_logrotate

if ! $app_install_inside_container && ([[ "$data" == "no" ]] || [[ "$metadata" == "no" ]])
then
	ynh_script_progression "Umount virtual disk..."
	# Remove the app directory securely
	umount_disk
fi

ynh_config_remove_nginx

#add wildcard subdomain
ynh_replace --match="server_name $domain" --replace="server_name $domain *.$domain" --file="/etc/nginx/conf.d/$domain.conf"
ynh_store_file_checksum "/etc/nginx/conf.d/$domain.conf"

ynh_safe_rm "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"

yunohost tools regen-conf nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
